//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosRFC
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public string RFC { get; set; }
        public System.DateTime FNacimiento { get; set; }

        private string nombreCompleto;
        public string NombreCompleto
        {
            get
            {
                if (Materno != null)
                {
                    nombreCompleto = $"{Nombre} {Paterno} {Materno}";
                }
                else
                {
                    nombreCompleto = $"{Nombre} {Paterno}";
                }
                return nombreCompleto;
            }
        }
        private string fechaN;
        public string FechaNacimiento
        {
            get
            {
                fechaN = FNacimiento.ToString("dd/MM/yyyy");
                return fechaN;
            }
        }

        public int Repetidos { get; set; }
        
        
        
    }
}
